apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-site-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: website.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-website
                port:
                  number: 80
