name: Build and Push Docker Image with Auto Versioning

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Important to fetch tags and full history

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get latest tag and bump version
      id: version
      run: |
        git fetch --tags
        latest_tag=$(git tag | grep '^v' | sort -V | tail -n 1)

        if [ -z "$latest_tag" ]; then
          new_tag="v1.0"
        elif [[ "$latest_tag" =~ ^v([0-9]+)\.([0-9]+)$ ]]; then
          major=${BASH_REMATCH[1]}
          minor=${BASH_REMATCH[2]}
          new_tag="v${major}.$((minor+1))"
        else
          echo "Unexpected tag format: $latest_tag"
          exit 1
        fi

        echo "Using tag: $new_tag"
        echo "tag=$new_tag" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        docker build -t mukiwa/gitops-demo:${{ steps.version.outputs.tag }} .

    - name: Push Docker image
      run: |
        docker push mukiwa/gitops-demo:${{ steps.version.outputs.tag }}

    - name: Push Git tag using GITHUB_TOKEN
      env:
        TAG: ${{ steps.version.outputs.tag }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag $TAG

        # Update origin URL with token for auth
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/Astonie/simple-website.git

        git push origin $TAG
