name: Build and Push Docker Image with Versioning

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # required to fetch tags

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get latest tag and bump version
      id: version
      run: |
        git fetch --tags
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "Latest tag: $latest_tag"
        if [[ "$latest_tag" =~ ^v([0-9]+)\.([0-9]+)$ ]]; then
          major=${BASH_REMATCH[1]}
          minor=${BASH_REMATCH[2]}
          new_tag="v${major}.$((minor+1))"
        else
          new_tag="v1.0"
        fi
        echo "New tag: $new_tag"
        echo "tag=$new_tag" >> $GITHUB_OUTPUT

    - name: Build Docker image with new version tag
      run: |
        docker build -f Dockerfile -t mukiwa/gitops-demo:${{ steps.version.outputs.tag }} .

    - name: Push Docker image to Docker Hub
      run: |
        docker push mukiwa/gitops-demo:${{ steps.version.outputs.tag }}

    - name: Create Git tag for new version
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag ${{ steps.version.outputs.tag }}
        git push origin ${{ steps.version.outputs.tag }}
